### ISSUE TITLE
Move Certs does not work with MagiskSU

### ISSUE THREAD

**Issue by carlylemiii** [Nutomic/movecerts#8]

**Comment by remewer** [comment]
It works for me. Android 7.0 Magisk 16.

**Comment by carlylemiii** [comment]
Whoops, guess I never closed this. It didn't on my Pixel in an early Magisk beta but it does now.

**Comment by remewer** [comment]
Somehow it stopped working in Magisk 16. Luckily, someone made a Magisk module https://forum.xda-developers.com/showpost.php?p=75835120&postcount=3039

**Comment by carlylemiii** [comment]
@remewer must be device specific, works for me on a Pixel 2 XL

**Comment by carlylemiii** [comment]
Doesn't really matter, AdGuard is adding this in 2.11
